const FILM_WORDS = [
  "ALIEN","AMOUR","ANNIE","ARIEL","AKIRA",
  "BABEL","BAMBI","BRAVE","BRICK","BULLY",
  "CAROL","CLICK","CRASH","CREED","DRIVE",
  "DUMBO","ENEMY","ELVIS","EVITA","FARGO",
  "JOKER","LOGAN","NIXON","MOANA","PEARL",
  "RANGO","RAMBO","ROCKY","SEVEN","SHREK",
  "SPLIT","SIGNS","SMILE","SPEED","SULLY",
  "TAKEN","TANGO","TENET","THIEF","WONKA",
  "ALIVE","ABYSS","LYNCH","NOLAN","PEELE",
  "WOODY","FRODO","GROOT","SIMBA","VADER",
  "DOBBY","AUDIO","BOOMS","CRANE","DOLLY",
  "FRAME","PROPS","REELS","SCENE","SCORE",
  "SOUND","STAGE","ANIME","CRIME","DRAMA",
  "INDIE","PIXAR","DAFOE","PESCI","KEANU","GADOT"
];

let ALL_VALID = new Set(FILM_WORDS);